# Command-line options can override these values.
device = 0
letters = 8
probability = 4
updates_per_second = 30
width = 1920
height = 1080
cell_size = 8
segmentation_threshold = 0.95
output = "preview"